---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: metacontroller.vmware.com.2.0.12+0
spec:
  refName: metacontroller.vmware.com
  version: 2.0.12+0
  releaseNotes: |
        Initial release of the metacontroller package
  licenses:
  - "Apache 2.0"
  releasedAt: 2021-11-12T18:27:28Z-5
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/cdelashmutt-pivotal/metacontroller-package:v2.0.12.0
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}